# Generated by Django 4.0.2 on 2022-03-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='views_count',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
